exports.games = [
    {
        title: 'Anthem',
        developer: 'BioWare',
        publisher: 'Electronic Arts',
        releaseDate: new Date(2019, 1, 22),
        genre: 'Action, RPG',
        art: '/images/anthem.jpg',
        reviews: [],
    },
    {
        title: 'Apex Legends',
        developer: 'Respawn Entertainment',
        publisher: 'Electronic Arts',
        releaseDate: new Date(2019, 1, 4),
        genre: 'Battle Royale, FPS',
        art: '/images/apexlegends.jpg',
        reviews: [],
    },
    {
        title: 'Call of Duty: Modern Warfare',
        developer: 'Infinity Ward',
        publisher: 'Activision',
        releaseDate: new Date(2019, 9, 25),
        genre: 'Action, FPS',
        art: '/images/modernwarfare.jpg',
        reviews: [],
    },
    {
        title: 'Hunt: Showdown',
        developer: 'Crytek',
        publisher: 'Crytek',
        releaseDate: new Date(2019, 7, 27),
        genre: 'FPS, Survival Horror',
        art: '/images/huntshowdown.jpg',
        reviews: [],
    },
    {
        title: 'Metro Exodus',
        developer: '4A Games',
        publisher: 'Deep Silver',
        releaseDate: new Date(2019, 1, 15),
        genre: 'Action, FPS',
        art: '/images/metroexodus.jpg',
        reviews: [],
    },
    {
        title: 'Mordhau',
        developer: 'Triternion',
        publisher: 'Triternion',
        releaseDate: new Date(2019, 3, 29),
        genre: 'Action, Indie',
        art: '/images/mordhau.jpg',
        reviews: [],
    },
    {
        title: 'Rainbow Six Siege',
        developer: 'Ubisoft Montreal',
        publisher: 'Ubisoft',
        releaseDate: new Date(2015, 11, 1),
        genre: 'Tactical Shooter',
        art: '/images/r6siege.jpg',
        reviews: [],
    },
    {
        title: 'Sekiro: Shadows Die Twice',
        developer: 'FromSoftware',
        publisher: 'Activision',
        releaseDate: new Date(2019, 2, 22),
        genre: 'Action, Adventure',
        art: '/images/sekiro.jpg',
        reviews: [],
    },
    {
        title: 'Total War: Three Kingdoms',
        developer: 'Creative Assembly',
        publisher: 'Sega',
        releaseDate: new Date(2019, 4, 23),
        genre: 'Real-time Tactics',
        art: '/images/threekingdoms.jpg',
        reviews: [],
    },
    {
        title: 'Wolcen: Lords of Mayhem',
        developer: 'Wolcen Studio',
        publisher: 'Wolcen Studio',
        releaseDate: new Date(2020, 1, 13),
        genre: 'Action RPG, Adventure, Indie',
        art: '/images/wolcen.jpg',
        reviews: [],
    }
];
