exports.games = [
    {
        title: 'Anthem',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Apex Legends',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Call of Duty: Modern Warfare',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Hunt: Showdown',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Metro Exodus',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Mordhau',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Rainbow Six Siege',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Sekiro: Shadows Die Twice',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Total War: Three Kingdoms',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    },
    {
        title: 'Wolcen',
        developer: '',
        publisher: '',
        releaseDate: new Date(),
        genre: '',
        platform: '',
        reviews: [],
    }
];
